Repository pix-el-wave/fooda-backend, pull requests merged in 2023-11, with the labels that each got.

#44 [#43] 사용자 프로필 정보 조회 기능
  src/main/java/inha/capstone/fooda/domain/feed/dto/PostFeedReqDto.java
  src/main/java/inha/capstone/fooda/domain/feed/repository/FeedRepository.java
  src/main/java/inha/capstone/fooda/domain/feed/service/FeedService.java
  src/main/java/inha/capstone/fooda/domain/feed_image/repository/FeedImageRepository.java
  src/main/java/inha/capstone/fooda/domain/feed_image/service/FeedImageService.java
  src/main/java/inha/capstone/fooda/domain/food/dto/PostFoodReqDto.java
  src/main/java/inha/capstone/fooda/domain/food/entity/Food.java
  src/main/java/inha/capstone/fooda/domain/friend/repository/FriendRepository.java
  src/main/java/inha/capstone/fooda/domain/friend/service/FriendService.java
  src/main/java/inha/capstone/fooda/domain/member/controller/MemberController.java
  src/main/java/inha/capstone/fooda/domain/member/dto/GetFindInfoMemberResDto.java
  src/main/java/inha/capstone/fooda/domain/member/dto/GetFindProfileInfoMemberResDto.java
  src/main/java/inha/capstone/fooda/domain/member/service/MemberService.java
  src/main/java/inha/capstone/fooda/utils/FeedImageResDto.java
  src/main/java/inha/capstone/fooda/utils/FoodListResDto.java
Labels: enhancement

#42 [#41] DB column 이름 수정 (table_column)
  src/main/java/inha/capstone/fooda/domain/feed/entity/Feed.java
  src/main/java/inha/capstone/fooda/domain/feed_image/entity/FeedImage.java
  src/main/java/inha/capstone/fooda/domain/food/entity/Food.java
  src/main/java/inha/capstone/fooda/domain/friend/entity/Friend.java
  src/main/java/inha/capstone/fooda/domain/member/entity/Member.java
Labels: enhancement

#45 [ #37 ] 팔로우 하는 사람들의 피드 기록 확인 API
  src/main/java/inha/capstone/fooda/domain/feed/controller/FeedController.java
  src/main/java/inha/capstone/fooda/domain/feed/dto/FeedDto.java
  src/main/java/inha/capstone/fooda/domain/feed/dto/GetSelectFeedFollowingResDto.java
  src/main/java/inha/capstone/fooda/domain/feed/dto/PostSelectFeedReqDto.java
  src/main/java/inha/capstone/fooda/domain/feed/repository/FeedRepository.java
  src/main/java/inha/capstone/fooda/domain/feed/service/FeedService.java
Labels: bug, enhancement

#48 [#47] FeedRepository에 누락된 함수 추가
  src/main/java/inha/capstone/fooda/domain/feed/repository/FeedRepository.java
Labels: bug

#49 [ #42, #37, #43, #36, #47 ] Deveop -> Main
  src/main/java/inha/capstone/fooda/domain/feed/controller/FeedController.java
  src/main/java/inha/capstone/fooda/domain/feed/dto/FeedDto.java
  src/main/java/inha/capstone/fooda/domain/feed/dto/GetSelectFeedFollowingResDto.java
  src/main/java/inha/capstone/fooda/domain/feed/dto/PostFeedReqDto.java
  src/main/java/inha/capstone/fooda/domain/feed/dto/PostSelectFeedReqDto.java
  src/main/java/inha/capstone/fooda/domain/feed/entity/Feed.java
  src/main/java/inha/capstone/fooda/domain/feed/repository/FeedRepository.java
  src/main/java/inha/capstone/fooda/domain/feed/service/FeedService.java
  src/main/java/inha/capstone/fooda/domain/feed_image/entity/FeedImage.java
  src/main/java/inha/capstone/fooda/domain/feed_image/repository/FeedImageRepository.java
  src/main/java/inha/capstone/fooda/domain/feed_image/service/FeedImageService.java
  src/main/java/inha/capstone/fooda/domain/food/dto/PostFoodReqDto.java
  src/main/java/inha/capstone/fooda/domain/food/entity/Food.java
  src/main/java/inha/capstone/fooda/domain/friend/entity/Friend.java
  src/main/java/inha/capstone/fooda/domain/friend/repository/FriendRepository.java
  src/main/java/inha/capstone/fooda/domain/friend/service/FriendService.java
  src/main/java/inha/capstone/fooda/domain/member/controller/MemberController.java
  src/main/java/inha/capstone/fooda/domain/member/dto/GetFindInfoMemberResDto.java
  src/main/java/inha/capstone/fooda/domain/member/dto/GetFindProfileInfoMemberResDto.java
  src/main/java/inha/capstone/fooda/domain/member/entity/Member.java
  src/main/java/inha/capstone/fooda/domain/member/service/MemberService.java
  src/main/java/inha/capstone/fooda/utils/FeedImageResDto.java
  src/main/java/inha/capstone/fooda/utils/FoodListResDto.java
Labels: bug, enhancement

#52 [ #51 ] 전체 피드 조회 API
  src/main/java/inha/capstone/fooda/domain/feed/controller/FeedController.java
  src/main/java/inha/capstone/fooda/domain/feed/dto/GetSelectFeedAllResDto.java
  src/main/java/inha/capstone/fooda/domain/feed/repository/FeedRepository.java
  src/main/java/inha/capstone/fooda/domain/feed/service/FeedService.java
Labels: enhancement

#53 [ #50 ] prod의 ddl-auto를 validate로 설정
  src/main/resources/application-prod.yml
Labels: enhancement

#54 [ #50, #51 ] Develop -> Main
  src/main/java/inha/capstone/fooda/domain/feed/controller/FeedController.java
  src/main/java/inha/capstone/fooda/domain/feed/dto/GetSelectFeedAllResDto.java
  src/main/java/inha/capstone/fooda/domain/feed/repository/FeedRepository.java
  src/main/java/inha/capstone/fooda/domain/feed/service/FeedService.java
  src/main/resources/application-prod.yml
Labels: enhancement

#56 [ #55 ] 누락된 ExceptionType 등록
  src/main/java/inha/capstone/fooda/domain/common/exception/ExceptionType.java
Labels: bug, enhancement

#59 [ #55, #27 ] Develop -> Main
  src/main/java/inha/capstone/fooda/domain/common/exception/ExceptionType.java
  src/main/java/inha/capstone/fooda/domain/friend/exception/FriendDuplicateException.java
  src/main/java/inha/capstone/fooda/domain/friend/repository/FriendRepository.java
  src/main/java/inha/capstone/fooda/domain/friend/service/FriendService.java
Labels: enhancement
